/*
 * Site wide keyword search for mainpage.html.
 *
 * Reads search-index.json, which is generated by tools/build-search-index.js.
 * The index is fetched lazily on first interaction so it never delays the
 * initial render of the page.
 */
(function () {
  'use strict';

  var input, clearBtn, chipsEl, resultsEl, statusEl, navContainer, navBoxes;
  var index = null;
  var loading = false;
  var activeCategory = -1; // -1 means all
  var lastResults = [];
  var cursor = -1;
  var debounce;

  var MAX_RESULTS = 60;
  var SNIPPET_PAD = 110;

  function ready(fn) {
    if (document.readyState !== 'loading') fn();
    else document.addEventListener('DOMContentLoaded', fn);
  }

  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  function escapeRe(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  /* ---- index loading ---------------------------------------------------- */

  function loadIndex() {
    if (index || loading) return Promise.resolve(index);
    loading = true;
    setStatus('Loading search index...');

    return fetch('search-index.json')
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (data) {
        index = data;
        loading = false;
        setStatus('');
        if (input.value.trim()) run(input.value);
        return index;
      })
      .catch(function (err) {
        loading = false;
        setStatus('Search index could not be loaded. ' + err.message);
      });
  }

  function setStatus(msg) {
    statusEl.textContent = msg || '';
    statusEl.style.display = msg ? 'block' : 'none';
  }

  /* ---- scoring ---------------------------------------------------------- */

  function countMatches(haystack, re) {
    var m = haystack.match(re);
    return m ? m.length : 0;
  }

  /*
   * Terms are matched on word boundaries, not as raw substrings. A whole word
   * hit scores far higher than a prefix hit, so searching "eve" ranks a section
   * about EVE JSON above one that merely says "event" many times, while "exfil"
   * still finds "exfiltration".
   */
  function compile(terms) {
    return terms.map(function (t) {
      var e = escapeRe(t);
      return {
        raw: t,
        // Global forms are used only with String.match, which ignores
        // lastIndex. The non global forms are used with .test, which would
        // otherwise carry lastIndex between calls and drop matches.
        exact: new RegExp('\\b' + e + '\\b', 'gi'),
        prefix: new RegExp('\\b' + e, 'gi'),
        exactT: new RegExp('\\b' + e + '\\b', 'i'),
        prefixT: new RegExp('\\b' + e, 'i'),
      };
    });
  }

  function search(query) {
    var terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length || !index) return [];

    var compiled = compile(terms);
    var phrase = query.toLowerCase().trim().replace(/\s+/g, ' ');
    var phraseRe = terms.length > 1
      ? new RegExp('\\b' + escapeRe(phrase).replace(/\\?\s/g, '\\s+'), 'gi')
      : null;
    var hits = [];

    index.pages.forEach(function (page, pi) {
      var pageTitle = page.t.toLowerCase();

      page.s.forEach(function (sec) {
        var heading = sec.h.toLowerCase();
        var text = sec.t.toLowerCase();
        var score = 0;
        var matchedAll = true;

        // Long sections accumulate incidental hits, so damp the body score by
        // length. Without this a single large reference table outranks the
        // section that is actually about the query.
        var lengthDamp = 1 / (1 + Math.log10(Math.max(1, text.length / 1200)));

        for (var i = 0; i < compiled.length; i++) {
          var c = compiled[i];
          var titleExact = c.exactT.test(pageTitle);
          var headExact = c.exactT.test(heading);
          var titlePrefix = titleExact || c.prefixT.test(pageTitle);
          var headPrefix = headExact || c.prefixT.test(heading);

          var exactN = countMatches(text, c.exact);
          var prefixN = countMatches(text, c.prefix);
          var prefixOnly = Math.max(0, prefixN - exactN);

          if (!titlePrefix && !headPrefix && !prefixN) {
            matchedAll = false;
            break;
          }

          if (titleExact) score += 60;
          else if (titlePrefix) score += 24;

          if (headExact) score += 45;
          else if (headPrefix) score += 18;

          score += Math.min(exactN, 8) * 4 * lengthDamp;
          score += Math.min(prefixOnly, 8) * 1.2 * lengthDamp;
        }

        if (!matchedAll) return;

        // Reward the whole query appearing verbatim.
        if (phraseRe) {
          if (countMatches(heading, phraseRe)) score += 90;
          if (countMatches(text, phraseRe)) score += 45 * lengthDamp;
        }

        hits.push({
          page: page,
          pageIndex: pi,
          section: sec,
          category: page.c,
          score: score,
          terms: terms,
        });
      });
    });

    hits.sort(function (a, b) {
      if (b.score !== a.score) return b.score - a.score;
      return a.page.t.localeCompare(b.page.t);
    });

    return hits;
  }

  /* ---- rendering -------------------------------------------------------- */

  function buildSnippet(text, terms) {
    var at = -1;
    var i, m;

    // Anchor on a whole word hit so the excerpt shows the real reason the
    // section ranked, falling back to a prefix hit only if there is no
    // whole word one anywhere in the section.
    for (i = 0; i < terms.length && at === -1; i++) {
      m = text.match(new RegExp('\\b' + escapeRe(terms[i]) + '\\b', 'i'));
      if (m) at = m.index;
    }
    for (i = 0; i < terms.length && at === -1; i++) {
      m = text.match(new RegExp('\\b' + escapeRe(terms[i]), 'i'));
      if (m) at = m.index;
    }
    if (at === -1) at = 0;

    var start = Math.max(0, at - SNIPPET_PAD);
    var end = Math.min(text.length, at + SNIPPET_PAD * 2);
    var slice = text.slice(start, end);

    // Avoid cutting mid word.
    if (start > 0) slice = slice.replace(/^\S*\s/, '');
    if (end < text.length) slice = slice.replace(/\s\S*$/, '');

    return (start > 0 ? '...' : '') + highlight(slice, terms) + (end < text.length ? '...' : '');
  }

  /*
   * Highlights at word boundaries. Whole word hits win, so searching "eve"
   * marks "EVE JSON" rather than lighting up every "event" on the line. A
   * prefix is only marked where the exact word appears nowhere in the string.
   */
  function highlight(str, terms) {
    var html = escapeHtml(str);
    terms.forEach(function (term) {
      var e = escapeRe(escapeHtml(term));
      var exact = new RegExp('\\b(' + e + ')\\b', 'gi');
      var re = exact.test(html) ? new RegExp('\\b(' + e + ')\\b', 'gi')
                                : new RegExp('\\b(' + e + ')', 'gi');
      html = html.replace(re, '<mark>$1</mark>');
    });
    return html;
  }

  function renderChips(hits, query) {
    if (!query) {
      chipsEl.innerHTML = '';
      chipsEl.style.display = 'none';
      return;
    }

    var counts = index.categories.map(function () { return 0; });
    hits.forEach(function (h) { counts[h.category]++; });

    var html = '<button class="htl-chip' + (activeCategory === -1 ? ' is-active' : '') +
      '" data-cat="-1">All <span>' + hits.length + '</span></button>';

    index.categories.forEach(function (cat, i) {
      if (!counts[i]) return;
      html += '<button class="htl-chip' + (activeCategory === i ? ' is-active' : '') +
        '" data-cat="' + i + '">' + escapeHtml(cat.label) + ' <span>' + counts[i] + '</span></button>';
    });

    chipsEl.innerHTML = html;
    chipsEl.style.display = 'flex';
  }

  function renderResults(hits, query) {
    if (!query) {
      resultsEl.innerHTML = '';
      resultsEl.style.display = 'none';
      return;
    }

    var shown = activeCategory === -1
      ? hits
      : hits.filter(function (h) { return h.category === activeCategory; });

    lastResults = shown.slice(0, MAX_RESULTS);
    cursor = -1;

    if (!shown.length) {
      resultsEl.innerHTML = '<div class="htl-empty">No matches for <strong>' +
        escapeHtml(query) + '</strong>. Try a single keyword such as <em>brute force</em>, ' +
        '<em>sysmon</em>, or <em>exfiltration</em>.</div>';
      resultsEl.style.display = 'block';
      return;
    }

    var html = '<div class="htl-results-meta">' + shown.length +
      (shown.length === 1 ? ' match' : ' matches') +
      (shown.length > MAX_RESULTS ? ', showing the top ' + MAX_RESULTS : '') + '</div>';

    lastResults.forEach(function (hit, i) {
      var cat = index.categories[hit.category];
      var href = hit.page.f + (hit.section.a ? '#' + hit.section.a : '');

      html += '<a class="htl-result" href="' + escapeHtml(href) + '" data-i="' + i + '">' +
        '<div class="htl-result-head">' +
          '<i class="fas ' + escapeHtml(cat.icon) + '"></i>' +
          '<span class="htl-result-page">' + highlight(hit.page.t, hit.terms) + '</span>' +
          '<span class="htl-result-sep">&rsaquo;</span>' +
          '<span class="htl-result-section">' + highlight(hit.section.h, hit.terms) + '</span>' +
          '<span class="htl-result-cat">' + escapeHtml(cat.label) + '</span>' +
        '</div>' +
        '<div class="htl-result-snippet">' + buildSnippet(hit.section.t, hit.terms) + '</div>' +
      '</a>';
    });

    resultsEl.innerHTML = html;
    resultsEl.style.display = 'block';
  }

  /* Dim category boxes that have no matches for the current query. */
  function filterNavBoxes(hits, query) {
    if (!query || !hits.length) {
      navBoxes.forEach(function (box) {
        box.classList.remove('is-dimmed', 'is-hit');
        var badge = box.querySelector('.nav-box-count');
        if (badge) badge.textContent = badge.dataset.total;
      });
      navContainer.classList.remove('is-filtering');
      return;
    }

    var counts = index.categories.map(function () { return 0; });
    hits.forEach(function (h) { counts[h.category]++; });

    navContainer.classList.add('is-filtering');
    navBoxes.forEach(function (box) {
      var i = parseInt(box.dataset.category, 10);
      var n = counts[i] || 0;
      box.classList.toggle('is-dimmed', n === 0);
      box.classList.toggle('is-hit', n > 0);
      var badge = box.querySelector('.nav-box-count');
      if (badge) badge.textContent = n ? n + ' match' + (n === 1 ? '' : 'es') : 'no matches';
    });
  }

  function run(rawQuery) {
    var query = rawQuery.trim();
    clearBtn.style.display = query ? 'flex' : 'none';

    if (!query) {
      renderChips([], '');
      renderResults([], '');
      filterNavBoxes([], '');
      return;
    }

    if (!index) {
      loadIndex();
      return;
    }

    var hits = search(query);
    renderChips(hits, query);
    renderResults(hits, query);
    filterNavBoxes(hits, query);
  }

  /* ---- keyboard --------------------------------------------------------- */

  function moveCursor(delta) {
    var nodes = resultsEl.querySelectorAll('.htl-result');
    if (!nodes.length) return;

    if (cursor >= 0 && nodes[cursor]) nodes[cursor].classList.remove('is-active');
    cursor += delta;
    if (cursor < 0) cursor = nodes.length - 1;
    if (cursor >= nodes.length) cursor = 0;

    nodes[cursor].classList.add('is-active');
    nodes[cursor].scrollIntoView({ block: 'nearest' });
  }

  /* ---- wiring ----------------------------------------------------------- */

  // Outside a browser this file is being required by the ranking tests, so
  // expose the scoring internals and skip all DOM wiring.
  if (typeof document === 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      module.exports = {
        setIndex: function (i) { index = i; },
        search: search,
        buildSnippet: buildSnippet,
        highlight: highlight,
      };
    }
    return;
  }

  ready(function () {
    input = document.getElementById('htl-search-input');
    if (!input) return;

    clearBtn = document.getElementById('htl-search-clear');
    chipsEl = document.getElementById('htl-search-chips');
    resultsEl = document.getElementById('htl-search-results');
    statusEl = document.getElementById('htl-search-status');
    navContainer = document.querySelector('.navigation-container');
    navBoxes = Array.prototype.slice.call(document.querySelectorAll('.nav-box'));

    navBoxes.forEach(function (box) {
      var badge = box.querySelector('.nav-box-count');
      if (badge) badge.dataset.total = badge.textContent;
    });

    input.addEventListener('focus', loadIndex, { once: true });

    input.addEventListener('input', function () {
      clearTimeout(debounce);
      var value = input.value;
      debounce = setTimeout(function () {
        activeCategory = -1;
        run(value);
      }, 120);
    });

    clearBtn.addEventListener('click', function () {
      input.value = '';
      activeCategory = -1;
      run('');
      input.focus();
    });

    chipsEl.addEventListener('click', function (e) {
      var chip = e.target.closest('.htl-chip');
      if (!chip) return;
      activeCategory = parseInt(chip.dataset.cat, 10);
      var hits = search(input.value.trim());
      renderChips(hits, input.value.trim());
      renderResults(hits, input.value.trim());
    });

    input.addEventListener('keydown', function (e) {
      if (e.key === 'ArrowDown') { e.preventDefault(); moveCursor(1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); moveCursor(-1); }
      else if (e.key === 'Enter') {
        var nodes = resultsEl.querySelectorAll('.htl-result');
        var target = cursor >= 0 ? nodes[cursor] : nodes[0];
        if (target) { e.preventDefault(); window.location.href = target.getAttribute('href'); }
      } else if (e.key === 'Escape') {
        input.value = '';
        activeCategory = -1;
        run('');
      }
    });

    // Slash focuses the search box from anywhere on the page.
    document.addEventListener('keydown', function (e) {
      if (e.key === '/' && document.activeElement !== input) {
        e.preventDefault();
        input.focus();
      }
    });
  });
})();
